### PR TITLE
Fix issue #21 check sql require primary key on

### LINKED ISSUE #21: Check sql_require_primary_key=on
For MySQL 8.0+, this should be set to on to avoid future agony.

```sql
SET_VAR(sql_require_primary_key=ON)
```

To do this, you'll need to create a new check in [src/Engine/Check/Database](https://github.com/xsist10/cadfael/tree/master/src/Engine/Check/Database) and get the database variables from `$entity->getVariables()`.

You can use [Check/Database/UnsupportedVersion.php](https://github.com/xsist10/cadfael/blob/master/src/Engine/Check/Database/UnsupportedVersion.php) as an example of how to build a check.

You will also need to add the new check [here](https://github.com/xsist10/cadfael/blob/master/src/Cli/Command/RunCommand.php#L112).

A unit test will also be needed to ensure the check works.

### PR DESCRIPTION
**Pull request by martijnengler**
Fix #21 by adding a warning when running on MySQL 8+ with sql_require_primary_key set to "OFF"

Includes tests

### CODE REVIEW

**Comment by xsist10** [comment]
Great work and thank you for this merge request.

File: src/Engine/Check/Database/RequirePrimaryKey.php [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+                    $e->getMessage(),
+                    "This makes us nervous."
+                ]
+            );
+        }
+
+        $variables = $entity->getVariables();
+        $opt_name = 'sql_require_primary_key';
+        $require_pk_disabled = (!isset($variables[$opt_name]) || $variables[$opt_name] !== 'ON');
+        if (version_compare($entity->getVersion(), '8.0.0', '>=') && $require_pk_disabled) {
```
Comment (xsist10) [inline src/Engine/Check/Database/RequirePrimaryKey.php:42]: FYI this was introduced in `8.0.13` (my bad for not checking [here](https://dev.mysql.com/doc/mysqld-version-reference/en/optvar-changes-8-0.html)) so if you want another hacktober MR, this is a quick one.

Comment (xsist10) [reply src/Engine/Check/Database/RequirePrimaryKey.php:42]: You can run it against your test environment database without `--performance_schema`. Certain checks won't run (like badly performing queries and inactive users) and others around capacity planning won't give relevant warnings, but the design checks will return valuable results.

**Comment by xsist10** [comment]
Quick note that I added the wiki documentation link for this check here: https://github.com/xsist10/cadfael/wiki/Force-Primary-Key-Requirement
